#!/bin/bash

if [[ -z $1 || "$1" == "-h" ]] ; then
  echo "This tool extracts Cartesian coordinates from a file generated by GaussView (gjf)."
  echo "The outputfile is in simple xmol format, which is understood by most visualisers."
  echo "Usage: ${0##*/} [debug] <input_file> [<output_file>]"
  echo "__version___: 2019-08-00-0000"
  exit 0
fi

if [[ "$1" == "debug" ]] ; then
  exec 3>&2
  shift
else
  exec 3> /dev/null
fi

debug ()
{
  echo "$*" >&3
}

warn ()
{
  echo "Warning: $*" >&2
}

fatal ()
{
  echo "Error: $*" >&2
  exit 1
}

check_element ()
{
  local -a elements_pattern
  # define periodic table of recognised patterns
  elements_pattern[0]="[Xx][Xx]?"   #Dummy
  elements_pattern[1]="[Hh]"        #Hydrogen
  elements_pattern[2]="[Hh][Ee]"    #Helium
  elements_pattern[3]="[Ll][Ii]"    #Lithium
  elements_pattern[4]="[Bb][Ee]"    #Beryllium
  elements_pattern[5]="[Bb]"        #Boron
  elements_pattern[6]="[Cc]"        #Carbon
  elements_pattern[7]="[Nn]"        #Nitrogen
  elements_pattern[8]="[Oo]"        #Oxygen
  elements_pattern[9]="[Ff]"        #Fluorine
  elements_pattern[10]="[Nn][Ee]"   #Neon
  elements_pattern[11]="[Nn][Aa]"   #Sodium
  elements_pattern[12]="[Mm][Gg]"   #Magnesium
  elements_pattern[13]="[Aa][Ll]"   #Aluminum
  elements_pattern[14]="[Ss][Ii]"   #Silicon
  elements_pattern[15]="[Pp]"       #Phosphorus
  elements_pattern[16]="[Ss]"       #Sulfur
  elements_pattern[17]="[Cc][Ll]"   #Chlorine
  elements_pattern[18]="[Aa][Rr]"   #Argon
  elements_pattern[19]="[Kk]"       #Potassium
  elements_pattern[20]="[Cc][Aa]"   #Calcium
  elements_pattern[21]="[Ss][Cc]"   #Scandium
  elements_pattern[22]="[Tt][Ii]"   #Titanium
  elements_pattern[23]="[Vv]"       #Vanadium
  elements_pattern[24]="[Cc][Rr]"   #Chromium
  elements_pattern[25]="[Mm][Nn]"   #Manganese
  elements_pattern[26]="[Ff][Ee]"   #Iron
  elements_pattern[27]="[Cc][Oo]"   #Cobalt
  elements_pattern[28]="[Nn][Ii]"   #Nickel
  elements_pattern[29]="[Cc][Uu]"   #Copper
  elements_pattern[30]="[Zz][Nn]"   #Zinc
  elements_pattern[31]="[Gg][Aa]"   #Gallium
  elements_pattern[32]="[Gg][Ee]"   #Germanium
  elements_pattern[33]="[Aa][Ss]"   #Arsenic
  elements_pattern[34]="[Ss][Ee]"   #Selenium
  elements_pattern[35]="[Bb][Rr]"   #Bromine
  elements_pattern[36]="[Kk][Rr]"   #Krypton
  elements_pattern[37]="[Rr][Bb]"   #Rubidium
  elements_pattern[38]="[Ss][Rr]"   #Strontium
  elements_pattern[39]="[Yy]"       #Yttrium
  elements_pattern[40]="[Zz][Rr]"   #Zirconium
  elements_pattern[41]="[Nn][Bb]"   #Niobium
  elements_pattern[42]="[Mm][Oo]"   #Molybdenum
  elements_pattern[43]="[Tt][Cc]"   #Technetium
  elements_pattern[44]="[Rr][Uu]"   #Ruthenium
  elements_pattern[45]="[Rr][Hh]"   #Rhodium
  elements_pattern[46]="[Pp][Dd]"   #Palladium
  elements_pattern[47]="[Aa][Gg]"   #Silver
  elements_pattern[48]="[Cc][Dd]"   #Cadmium
  elements_pattern[49]="[Ii][Nn]"   #Indium
  elements_pattern[50]="[Ss][Nn]"   #Tin
  elements_pattern[51]="[Ss][Bb]"   #Antimony
  elements_pattern[52]="[Tt][Ee]"   #Tellurium
  elements_pattern[53]="[Ii]"       #Iodine
  elements_pattern[54]="[Xx][Ee]"   #Xenon
  elements_pattern[55]="[Cc][Ss]"   #Cesium
  elements_pattern[56]="[Bb][Aa]"   #Barium
  elements_pattern[57]="[Ll][Aa]"   #Lanthanum
  elements_pattern[58]="[Cc][Ee]"   #Cerium
  elements_pattern[59]="[Pp][Rr]"   #Praseodymium
  elements_pattern[60]="[Nn][Dd]"   #Neodymium
  elements_pattern[61]="[Pp][Mm]"   #Promethium
  elements_pattern[62]="[Ss][Mm]"   #Samarium
  elements_pattern[63]="[Ee][Uu]"   #Europium
  elements_pattern[64]="[Gg][Dd]"   #Gadolinium
  elements_pattern[65]="[Tt][Bb]"   #Terbium
  elements_pattern[66]="[Dd][Yy]"   #Dysprosium
  elements_pattern[67]="[Hh][Oo]"   #Holmium
  elements_pattern[68]="[Ee][Rr]"   #Erbium
  elements_pattern[69]="[Tt][Mm]"   #Thulium
  elements_pattern[70]="[Yy][Bb]"   #Ytterbium
  elements_pattern[71]="[Ll][Uu]"   #Lutetium
  elements_pattern[72]="[Hh][Ff]"   #Hafnium
  elements_pattern[73]="[Tt][Aa]"   #Tantalum
  elements_pattern[74]="[Ww]"       #Tungsten
  elements_pattern[75]="[Rr][Ee]"   #Rhenium
  elements_pattern[76]="[Oo][Ss]"   #Osmium
  elements_pattern[77]="[Ii][Rr]"   #Iridium
  elements_pattern[78]="[Pp][Tt]"   #Platinum
  elements_pattern[79]="[Aa][Uu]"   #Gold
  elements_pattern[80]="[Hh][Gg]"   #Mercury
  elements_pattern[81]="[Tt][Ll]"   #Thallium
  elements_pattern[82]="[Pp][Bb]"   #Lead
  elements_pattern[83]="[Bb][Ii]"   #Bismuth
  elements_pattern[84]="[Pp][Oo]"   #Polonium
  elements_pattern[85]="[Aa][Tt]"   #Astatine
  elements_pattern[86]="[Rr][Nn]"   #Radon
  elements_pattern[87]="[Ff][Rr]"   #Francium
  elements_pattern[88]="[Rr][Aa]"   #Radium
  elements_pattern[89]="[Aa][Cc]"   #Actinium
  elements_pattern[90]="[Tt][Hh]"   #Thorium
  elements_pattern[91]="[Pp][Aa]"   #Protactinium
  elements_pattern[92]="[Uu]"       #Uranium
  elements_pattern[93]="[Nn][Pp]"   #Neptunium
  elements_pattern[94]="[Pp][Uu]"   #Plutonium
  elements_pattern[95]="[Aa][Mm]"   #Americium
  elements_pattern[96]="[Cc][Mm]"   #Curium
  elements_pattern[97]="[Bb][Kk]"   #Berkelium
  elements_pattern[98]="[Cc][Ff]"   #Californium
  elements_pattern[99]="[Ee][Ss]"   #Einsteinium
  elements_pattern[100]="[Ff][Mm]"  #Fermium
  elements_pattern[101]="[Mm][Dd]"  #Mendelevium
  elements_pattern[102]="[Nn][Oo]"  #Nobelium
  elements_pattern[103]="[Ll][Rr]"  #Lawrencium
  elements_pattern[104]="[Rr][Ff]"  #Rutherfordium
  elements_pattern[105]="[Dd][Bb]"  #Dubnium
  elements_pattern[106]="[Ss][Gg]"  #Seaborgium
  elements_pattern[107]="[Bb][Hh]"  #Bohrium
  elements_pattern[108]="[Hh][Ss]"  #Hassium
  elements_pattern[109]="[Mm][Tt]"  #Meitnerium
  elements_pattern[110]="[Dd][Ss]"  #Darmstadtium
  elements_pattern[111]="[Rr][Gg]"  #Roentgenium
  elements_pattern[112]="[Cc][Nn]"  #Copernicium
  elements_pattern[113]="[Nn][Hh]"  #Nihonium
  elements_pattern[114]="[Ff][Ll]"  #Flerovium
  elements_pattern[115]="[Mm][Cc]"  #Moscovium
  elements_pattern[116]="[Ll][Vv]"  #Livermorium
  elements_pattern[117]="[Tt][Ss]"  #Tennessine
  elements_pattern[118]="[Oo][Gg]"  #Oganesson
  
  local pattern_checkelement
  local test_element="$1"
  for pattern_checkelement in "${elements_pattern[@]}" ; do
    if [[ "$test_element" =~ $pattern_checkelement ]] ; then
      debug "Info: Recognised element '$test_element'."
      return 0
    fi
  done
  debug "Warning: Unrecognised element '$test_element'."
  return 1
}

extract_coordinates ()
{ 
  # Converts Cartesian coordinates in gjf format to xmol format
  local -a coordinates
  local    pattern pattern_num pattern_element
  local    pattern_print="%-3s %15.8f %15.8f %15.8f"
  local    print_element print_xxx print_yyy print_zzz
  local    storeline
  local    inputfile outputfile_defined outputfile
  
  inputfile="$1"
  outputfile_defined="$2"
  outputfile="${outputfile_defined:-${inputfile%.gjf}.xyz}"
  debug "inputfile=$inputfile; outputfile=$outputfile"
  
  pattern_num="[+-]?[0-9]+\\.[0-9]*"
  pattern_element="[A-Za-z]+[A-Za-z]?"
  pattern="^[[:space:]]*($pattern_element)[[:space:]]+($pattern_num)[[:space:]]+($pattern_num)[[:space:]]+($pattern_num)[[:space:]]*(.*)$"
  while read -r line || [[ -n "$line" ]] ; do
    debug "Read line: $line"
    if [[ "$line" =~ $pattern ]] ; then
      print_element="${BASH_REMATCH[1]}" 
      print_xxx="${BASH_REMATCH[2]}" 
      print_yyy="${BASH_REMATCH[3]}" 
      print_zzz="${BASH_REMATCH[4]}"
      [[ -z ${BASH_REMATCH[5]} ]] || debug "Ignored end of line: '${BASH_REMATCH[5]}'."
      if ! check_element "$print_element" ; then
        warn "Unrecognised element '$print_element'."
      fi

      # shellcheck disable=SC2059
      storeline=$(printf "$pattern_print" "$print_element" "$print_xxx" "$print_yyy" "$print_zzz")
      coordinates+=( "$storeline" )
      debug "Read and stored: '${coordinates[-1]}'"
      continue
    else
      debug "Line doesn't match pattern of xyz."
    fi
  done < "$inputfile"
  
  [[ -s "$outputfile" ]] && fatal "Cowardly refuse to overwrite non-empty file '$outputfile'."
  { 
    printf '%-5u\n%s\n' "${#coordinates[@]}" "Converted from $inputfile"
    printf '%s\n' "${coordinates[@]}" 
  } > "$outputfile"
}

#
# M A I N
#

[[ -z $1 ]] && fatal "No file specified."
extract_coordinates "$1" "$2"


